"""Add Session State Machine

Revision ID: 3ce1a438097d
Revises: 94476e77985c
Create Date: 2026-07-13 22:36:28.598584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ce1a438097d'
down_revision: Union[str, Sequence[str], None] = '94476e77985c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('CREATED', 'WAITING_FOR_DOCUMENT', 'DOCUMENT_CLASSIFIED', 'DOCUMENT_VALIDATED', 'OCR_COMPLETED', 'AGE_VERIFIED', 'FACE_CAPTURED', 'FACE_VERIFIED', 'DATABASE_CHECKED', 'RISK_EVALUATED', 'APPROVED', 'MANUAL_REVIEW', 'FRAUD_REVIEW', 'DENIED', 'COMPLETED', 'FAILED', name='sessionstateenum'), nullable=True),
    sa.Column('id_image_path', sa.String(), nullable=True),
    sa.Column('face_image_path', sa.String(), nullable=True),
    sa.Column('id_image_checksum', sa.String(), nullable=True),
    sa.Column('face_image_checksum', sa.String(), nullable=True),
    sa.Column('ocr_data', sa.JSON(), nullable=True),
    sa.Column('quality_scores', sa.JSON(), nullable=True),
    sa.Column('face_similarity', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('final_decision', sa.String(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_sessions_id'), ['id'], unique=False)

    op.create_table('session_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('state_from', sa.String(), nullable=True),
    sa.Column('state_to', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['verification_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_audit_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_logs_id'))

    op.drop_table('verification_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_recommendation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_authenticity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_ocr_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id_image_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('face_image_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('staff_decision', postgresql.ENUM('pass_decision', 'deny_decision', 'check_decision', name='decisionenum'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('verification_logs_customer_id_fkey')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('verification_logs_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_logs_pkey'))
    )
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('session_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_audit_logs_id'))

    op.drop_table('session_audit_logs')
    with op.batch_alter_table('verification_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_sessions_id'))

    op.drop_table('verification_sessions')
    # ### end Alembic commands ###
