"""Add SupervisorNote

Revision ID: 41284a3271f9
Revises: ab62ca54b6b7
Create Date: 2026-07-13 22:52:59.315593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41284a3271f9'
down_revision: Union[str, Sequence[str], None] = 'ab62ca54b6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('note_text', sa.String(), nullable=True),
    sa.Column('evidence_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['verification_sessions.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supervisor_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supervisor_notes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supervisor_notes_id'))

    op.drop_table('supervisor_notes')
    # ### end Alembic commands ###
