"""Add Explainability Report

Revision ID: 68e4b319f95e
Revises: 41284a3271f9
Create Date: 2026-07-13 22:54:13.950341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e4b319f95e'
down_revision: Union[str, Sequence[str], None] = '41284a3271f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explainability_report', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_sessions', schema=None) as batch_op:
        batch_op.drop_column('explainability_report')

    # ### end Alembic commands ###
