import pgvector.sqlalchemy
"""Initial schema

Revision ID: 94476e77985c
Revises: 
Create Date: 2026-07-13 22:25:14.887777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94476e77985c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('face_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('vip_tier', sa.String(), nullable=True),
    sa.Column('manager_notes', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_unique_id'), ['unique_id'], unique=True)

    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venues_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_name'), ['name'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('doc_number', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_doc_number'), ['doc_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_id'), ['id'], unique=False)

    op.create_table('policy_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('minimum_age', sa.Integer(), nullable=True),
    sa.Column('require_face_match', sa.Boolean(), nullable=True),
    sa.Column('face_similarity_threshold', sa.Float(), nullable=True),
    sa.Column('ocr_confidence_threshold', sa.Float(), nullable=True),
    sa.Column('quality_threshold', sa.Float(), nullable=True),
    sa.Column('blacklist_policy', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id')
    )
    with op.batch_alter_table('policy_schemas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_schemas_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'venue_admin', 'manager', 'door_staff', 'viewer', name='roleenum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('venue_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('allowed_documents', sa.JSON(), nullable=True),
    sa.Column('retention_days_success', sa.Integer(), nullable=True),
    sa.Column('retention_days_manual', sa.Integer(), nullable=True),
    sa.Column('retention_days_incident', sa.Integer(), nullable=True),
    sa.Column('verification_mode', sa.String(), nullable=True),
    sa.Column('theme_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id')
    )
    with op.batch_alter_table('venue_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_configurations_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('blacklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('manager_notes', sa.Text(), nullable=True),
    sa.Column('banned_by_id', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklists_id'), ['id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('incident_type', sa.Enum('violence', 'fake_id', 'property_damage', 'drug_related', 'other', name='incidenttypeenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_id'), ['id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_refresh_token'), ['refresh_token'], unique=False)

    op.create_table('verification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('ai_recommendation', sa.String(), nullable=True),
    sa.Column('ai_authenticity_score', sa.Float(), nullable=True),
    sa.Column('ai_quality_score', sa.Float(), nullable=True),
    sa.Column('ai_ocr_confidence', sa.Float(), nullable=True),
    sa.Column('id_image_path', sa.String(), nullable=True),
    sa.Column('face_image_path', sa.String(), nullable=True),
    sa.Column('staff_decision', sa.Enum('pass_decision', 'deny_decision', 'check_decision', name='decisionenum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_logs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_logs_id'))

    op.drop_table('verification_logs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_sessions_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('blacklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklists_id'))

    op.drop_table('blacklists')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('venue_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_configurations_id'))

    op.drop_table('venue_configurations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('policy_schemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_schemas_id'))

    op.drop_table('policy_schemas')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_number'))

    op.drop_table('documents')
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venues_name'))
        batch_op.drop_index(batch_op.f('ix_venues_id'))

    op.drop_table('venues')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_unique_id'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))

    op.drop_table('customers')
    # ### end Alembic commands ###
