"""add occupancy tracking

Revision ID: a64f7462df04
Revises: 91dc22841a72
Create Date: 2026-08-18 22:43:27.739666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64f7462df04'
down_revision: Union[str, Sequence[str], None] = '91dc22841a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupancy_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('INSIDE', 'CHECKED_OUT', 'AUTO_EXPIRED', name='occupancystatusenum'), nullable=True),
    sa.Column('checked_out_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checked_out_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['verification_sessions.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupancy_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupancy_records_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_occupancy_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_occupancy_records_venue_id'), ['venue_id'], unique=False)
        batch_op.create_index('ix_occupancy_venue_open', ['venue_id', 'exited_at'], unique=False)

    with op.batch_alter_table('venue_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupancy_auto_expire_hours', sa.Integer(), nullable=True, server_default='6'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue_configurations', schema=None) as batch_op:
        batch_op.drop_column('occupancy_auto_expire_hours')

    with op.batch_alter_table('occupancy_records', schema=None) as batch_op:
        batch_op.drop_index('ix_occupancy_venue_open')
        batch_op.drop_index(batch_op.f('ix_occupancy_records_venue_id'))
        batch_op.drop_index(batch_op.f('ix_occupancy_records_id'))
        batch_op.drop_index(batch_op.f('ix_occupancy_records_customer_id'))

    op.drop_table('occupancy_records')
    # ### end Alembic commands ###
