"""Add Daily Venue Metrics

Revision ID: ab62ca54b6b7
Revises: 3ce1a438097d
Create Date: 2026-07-13 22:52:20.622738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab62ca54b6b7'
down_revision: Union[str, Sequence[str], None] = '3ce1a438097d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_venue_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('total_verifications', sa.Integer(), nullable=True),
    sa.Column('approved_count', sa.Integer(), nullable=True),
    sa.Column('denied_count', sa.Integer(), nullable=True),
    sa.Column('manual_review_count', sa.Integer(), nullable=True),
    sa.Column('fraud_review_count', sa.Integer(), nullable=True),
    sa.Column('avg_verification_time_ms', sa.Float(), nullable=True),
    sa.Column('avg_ocr_time_ms', sa.Float(), nullable=True),
    sa.Column('avg_face_time_ms', sa.Float(), nullable=True),
    sa.Column('ocr_failure_count', sa.Integer(), nullable=True),
    sa.Column('face_failure_count', sa.Integer(), nullable=True),
    sa.Column('low_quality_image_count', sa.Integer(), nullable=True),
    sa.Column('blacklist_hits', sa.Integer(), nullable=True),
    sa.Column('document_types', sa.JSON(), nullable=True),
    sa.Column('age_distribution', sa.JSON(), nullable=True),
    sa.Column('device_usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_venue_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_venue_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_venue_metrics_record_date'), ['record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_venue_metrics_venue_id'), ['venue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_venue_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_venue_metrics_venue_id'))
        batch_op.drop_index(batch_op.f('ix_daily_venue_metrics_record_date'))
        batch_op.drop_index(batch_op.f('ix_daily_venue_metrics_id'))

    op.drop_table('daily_venue_metrics')
    # ### end Alembic commands ###
